
#ifndef __XINDOWSUTIL_ENCODE_MIME64_H__
#define __XINDOWSUTIL_ENCODE_MIME64_H__

XINDOWS_PUBLIC HRESULT Mime64Decode(LPCTSTR pStrData, LPSTREAM* ppstm);
XINDOWS_PUBLIC HRESULT Mime64Encode(LPBYTE pData, UINT cbData, LPTSTR pchData);

#endif //__XINDOWSUTIL_ENCODE_MIME64_H__