
#ifndef __XINDOWSUTIL_STREAM_BUFFERSTREAM_H__
#define __XINDOWSUTIL_STREAM_BUFFERSTREAM_H__

XINDOWS_PUBLIC IStream* CreateBufferStream(IStream* pStm);

#endif //__XINDOWSUTIL_STREAM_BUFFERSTREAM_H__