
#ifndef __XINDOWSUTIL_STREAM_FATSTG_H__
#define __XINDOWSUTIL_STREAM_FATSTG_H__

XINDOWS_PUBLIC HRESULT CreateStreamOnFile(LPCTSTR pchFile, DWORD dwSTGM, LPSTREAM* ppstrm);
XINDOWS_PUBLIC HRESULT CloseStreamOnFile(LPSTREAM pStm);

#endif //__XINDOWSUTIL_STREAM_FATSTG_H__
