
#ifndef __TESTXINDOWS_CORE_COLLECTIONTEST_H__
#define __TESTXINDOWS_CORE_COLLECTIONTEST_H__

XINDOWS_PUBLIC void TestAssocArray();

XINDOWS_PUBLIC void TestArray();

#endif	//__TESTXINDOWS_CORE_COLLECTIONTEST_H__